// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/messenger/messenger_service.proto

package api

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Peer    *Peer  `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*SendMessageResponse_Message
	Response isSendMessageResponse_Response `protobuf_oneof:"response"`
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{1}
}

func (m *SendMessageResponse) GetResponse() isSendMessageResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *SendMessageResponse) GetMessage() *Message {
	if x, ok := x.GetResponse().(*SendMessageResponse_Message); ok {
		return x.Message
	}
	return nil
}

type isSendMessageResponse_Response interface {
	isSendMessageResponse_Response()
}

type SendMessageResponse_Message struct {
	Message *Message `protobuf:"bytes,1,opt,name=message,proto3,oneof"`
}

func (*SendMessageResponse_Message) isSendMessageResponse_Response() {}

type ReadMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer   *Peer  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	LastId string `protobuf:"bytes,2,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
}

func (x *ReadMessageRequest) Reset() {
	*x = ReadMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageRequest) ProtoMessage() {}

func (x *ReadMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageRequest.ProtoReflect.Descriptor instead.
func (*ReadMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{2}
}

func (x *ReadMessageRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *ReadMessageRequest) GetLastId() string {
	if x != nil {
		return x.LastId
	}
	return ""
}

type ReadMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReadMessageResponse) Reset() {
	*x = ReadMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMessageResponse) ProtoMessage() {}

func (x *ReadMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMessageResponse.ProtoReflect.Descriptor instead.
func (*ReadMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{3}
}

type GetDialogRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer *Peer `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
}

func (x *GetDialogRequest) Reset() {
	*x = GetDialogRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogRequest) ProtoMessage() {}

func (x *GetDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogRequest.ProtoReflect.Descriptor instead.
func (*GetDialogRequest) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDialogRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type GetDialogResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dialog      *Dialog  `protobuf:"bytes,1,opt,name=dialog,proto3" json:"dialog,omitempty"`
	LastMessage *Message `protobuf:"bytes,2,opt,name=last_message,json=lastMessage,proto3,oneof" json:"last_message,omitempty"`
	User        *User    `protobuf:"bytes,3,opt,name=user,proto3,oneof" json:"user,omitempty"`
}

func (x *GetDialogResponse) Reset() {
	*x = GetDialogResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogResponse) ProtoMessage() {}

func (x *GetDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogResponse.ProtoReflect.Descriptor instead.
func (*GetDialogResponse) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDialogResponse) GetDialog() *Dialog {
	if x != nil {
		return x.Dialog
	}
	return nil
}

func (x *GetDialogResponse) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

func (x *GetDialogResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetDialogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OffsetDate *timestamp.Timestamp `protobuf:"bytes,1,opt,name=offset_date,json=offsetDate,proto3" json:"offset_date,omitempty"`
	Limit      int32                `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetDialogsRequest) Reset() {
	*x = GetDialogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogsRequest) ProtoMessage() {}

func (x *GetDialogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogsRequest.ProtoReflect.Descriptor instead.
func (*GetDialogsRequest) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetDialogsRequest) GetOffsetDate() *timestamp.Timestamp {
	if x != nil {
		return x.OffsetDate
	}
	return nil
}

func (x *GetDialogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetDialogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Dialogs:
	//
	//	*GetDialogsResponse_NotModified
	//	*GetDialogsResponse_Slice
	Dialogs isGetDialogsResponse_Dialogs `protobuf_oneof:"dialogs"`
}

func (x *GetDialogsResponse) Reset() {
	*x = GetDialogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDialogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDialogsResponse) ProtoMessage() {}

func (x *GetDialogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDialogsResponse.ProtoReflect.Descriptor instead.
func (*GetDialogsResponse) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{7}
}

func (m *GetDialogsResponse) GetDialogs() isGetDialogsResponse_Dialogs {
	if m != nil {
		return m.Dialogs
	}
	return nil
}

func (x *GetDialogsResponse) GetNotModified() *DialogsNotModified {
	if x, ok := x.GetDialogs().(*GetDialogsResponse_NotModified); ok {
		return x.NotModified
	}
	return nil
}

func (x *GetDialogsResponse) GetSlice() *DialogsSlice {
	if x, ok := x.GetDialogs().(*GetDialogsResponse_Slice); ok {
		return x.Slice
	}
	return nil
}

type isGetDialogsResponse_Dialogs interface {
	isGetDialogsResponse_Dialogs()
}

type GetDialogsResponse_NotModified struct {
	NotModified *DialogsNotModified `protobuf:"bytes,1,opt,name=not_modified,json=notModified,proto3,oneof"`
}

type GetDialogsResponse_Slice struct {
	Slice *DialogsSlice `protobuf:"bytes,2,opt,name=slice,proto3,oneof"`
}

func (*GetDialogsResponse_NotModified) isGetDialogsResponse_Dialogs() {}

func (*GetDialogsResponse_Slice) isGetDialogsResponse_Dialogs() {}

type DialogsNotModified struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *DialogsNotModified) Reset() {
	*x = DialogsNotModified{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogsNotModified) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogsNotModified) ProtoMessage() {}

func (x *DialogsNotModified) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogsNotModified.ProtoReflect.Descriptor instead.
func (*DialogsNotModified) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{8}
}

func (x *DialogsNotModified) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DialogsSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total    int32      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Dialogs  []*Dialog  `protobuf:"bytes,2,rep,name=dialogs,proto3" json:"dialogs,omitempty"`
	Messages []*Message `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Users    []*User    `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *DialogsSlice) Reset() {
	*x = DialogsSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DialogsSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DialogsSlice) ProtoMessage() {}

func (x *DialogsSlice) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DialogsSlice.ProtoReflect.Descriptor instead.
func (*DialogsSlice) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{9}
}

func (x *DialogsSlice) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DialogsSlice) GetDialogs() []*Dialog {
	if x != nil {
		return x.Dialogs
	}
	return nil
}

func (x *DialogsSlice) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *DialogsSlice) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer     *Peer   `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	OffsetId *string `protobuf:"bytes,2,opt,name=offset_id,json=offsetId,proto3,oneof" json:"offset_id,omitempty"`
	Limit    int32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessagesRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *GetMessagesRequest) GetOffsetId() string {
	if x != nil && x.OffsetId != nil {
		return *x.OffsetId
	}
	return ""
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Messages:
	//
	//	*GetMessagesResponse_NotModified
	//	*GetMessagesResponse_Slice
	Messages isGetMessagesResponse_Messages `protobuf_oneof:"messages"`
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{11}
}

func (m *GetMessagesResponse) GetMessages() isGetMessagesResponse_Messages {
	if m != nil {
		return m.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetNotModified() *MessagesNotModified {
	if x, ok := x.GetMessages().(*GetMessagesResponse_NotModified); ok {
		return x.NotModified
	}
	return nil
}

func (x *GetMessagesResponse) GetSlice() *MessagesSlice {
	if x, ok := x.GetMessages().(*GetMessagesResponse_Slice); ok {
		return x.Slice
	}
	return nil
}

type isGetMessagesResponse_Messages interface {
	isGetMessagesResponse_Messages()
}

type GetMessagesResponse_NotModified struct {
	NotModified *MessagesNotModified `protobuf:"bytes,1,opt,name=not_modified,json=notModified,proto3,oneof"`
}

type GetMessagesResponse_Slice struct {
	Slice *MessagesSlice `protobuf:"bytes,2,opt,name=slice,proto3,oneof"`
}

func (*GetMessagesResponse_NotModified) isGetMessagesResponse_Messages() {}

func (*GetMessagesResponse_Slice) isGetMessagesResponse_Messages() {}

type MessagesNotModified struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *MessagesNotModified) Reset() {
	*x = MessagesNotModified{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagesNotModified) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesNotModified) ProtoMessage() {}

func (x *MessagesNotModified) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesNotModified.ProtoReflect.Descriptor instead.
func (*MessagesNotModified) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{12}
}

func (x *MessagesNotModified) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MessagesSlice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total    int32      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Messages []*Message `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Users    []*User    `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *MessagesSlice) Reset() {
	*x = MessagesSlice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessagesSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesSlice) ProtoMessage() {}

func (x *MessagesSlice) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesSlice.ProtoReflect.Descriptor instead.
func (*MessagesSlice) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{13}
}

func (x *MessagesSlice) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MessagesSlice) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *MessagesSlice) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUnreadDialogsCounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUnreadDialogsCounterRequest) Reset() {
	*x = GetUnreadDialogsCounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnreadDialogsCounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadDialogsCounterRequest) ProtoMessage() {}

func (x *GetUnreadDialogsCounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadDialogsCounterRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadDialogsCounterRequest) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{14}
}

type GetUnreadDialogsCounterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetUnreadDialogsCounterResponse) Reset() {
	*x = GetUnreadDialogsCounterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_messenger_messenger_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUnreadDialogsCounterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadDialogsCounterResponse) ProtoMessage() {}

func (x *GetUnreadDialogsCounterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_messenger_messenger_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadDialogsCounterResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadDialogsCounterResponse) Descriptor() ([]byte, []int) {
	return file_api_messenger_messenger_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetUnreadDialogsCounterResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_api_messenger_messenger_service_proto protoreflect.FileDescriptor

var file_api_messenger_messenger_service_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x1a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65,
	0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x18, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x70,
	0x65, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x57,
	0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27,
	0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0x55, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x56,
	0x0a, 0x12, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67,
	0x65, 0x72, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3b, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x27, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e,
	0x50, 0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x22, 0xc6, 0x01, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x06, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x06, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x12,
	0x3e, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52,
	0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x28, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x01,
	0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x66, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73,
	0x4e, 0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x6e,
	0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x05, 0x73, 0x6c,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67,
	0x73, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x42,
	0x09, 0x0a, 0x07, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x2a, 0x0a, 0x12, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x73, 0x4e, 0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0xb0, 0x01, 0x0a, 0x0c, 0x44, 0x69, 0x61, 0x6c, 0x6f,
	0x67, 0x73, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x2f, 0x0a,
	0x07, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x07, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x32,
	0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x27, 0x0a, 0x04, 0x70, 0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x50,
	0x65, 0x65, 0x72, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x09, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08,
	0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x22,
	0xa0, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0c, 0x6e, 0x6f, 0x74, 0x5f, 0x6d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x4e, 0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x0b, 0x6e, 0x6f, 0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x12, 0x34, 0x0a, 0x05, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x22, 0x2b, 0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x4e, 0x6f,
	0x74, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22,
	0x80, 0x01, 0x0a, 0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x53, 0x6c, 0x69, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x32, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x22, 0x20, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61,
	0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0x8c, 0x06,
	0x0a, 0x09, 0x4d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x12, 0x77, 0x0a, 0x0b, 0x53,
	0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x6e,
	0x64, 0x3a, 0x01, 0x2a, 0x12, 0x77, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1b, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x72, 0x65, 0x61, 0x64, 0x3a, 0x01, 0x2a, 0x12, 0x70, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x69, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x12, 0x18, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x64, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x12,
	0x74, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x20, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x12, 0x19, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x64, 0x69,
	0x61, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x78, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65,
	0x6e, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1c, 0x12, 0x1a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12,
	0xaa, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x55, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x44, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x2d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x6e, 0x72, 0x65, 0x61, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x6e,
	0x72, 0x65, 0x61, 0x64, 0x44, 0x69, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x2a, 0x12, 0x28, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x65, 0x6e, 0x67, 0x65, 0x72, 0x2f, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x64, 0x2d, 0x64, 0x69, 0x61,
	0x6c, 0x6f, 0x67, 0x73, 0x2d, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x42, 0x19, 0x5a, 0x17,
	0x6d, 0x65, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x2a,
	0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_messenger_messenger_service_proto_rawDescOnce sync.Once
	file_api_messenger_messenger_service_proto_rawDescData = file_api_messenger_messenger_service_proto_rawDesc
)

func file_api_messenger_messenger_service_proto_rawDescGZIP() []byte {
	file_api_messenger_messenger_service_proto_rawDescOnce.Do(func() {
		file_api_messenger_messenger_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_messenger_messenger_service_proto_rawDescData)
	})
	return file_api_messenger_messenger_service_proto_rawDescData
}

var file_api_messenger_messenger_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_messenger_messenger_service_proto_goTypes = []interface{}{
	(*SendMessageRequest)(nil),              // 0: api.messenger.SendMessageRequest
	(*SendMessageResponse)(nil),             // 1: api.messenger.SendMessageResponse
	(*ReadMessageRequest)(nil),              // 2: api.messenger.ReadMessageRequest
	(*ReadMessageResponse)(nil),             // 3: api.messenger.ReadMessageResponse
	(*GetDialogRequest)(nil),                // 4: api.messenger.GetDialogRequest
	(*GetDialogResponse)(nil),               // 5: api.messenger.GetDialogResponse
	(*GetDialogsRequest)(nil),               // 6: api.messenger.GetDialogsRequest
	(*GetDialogsResponse)(nil),              // 7: api.messenger.GetDialogsResponse
	(*DialogsNotModified)(nil),              // 8: api.messenger.DialogsNotModified
	(*DialogsSlice)(nil),                    // 9: api.messenger.DialogsSlice
	(*GetMessagesRequest)(nil),              // 10: api.messenger.GetMessagesRequest
	(*GetMessagesResponse)(nil),             // 11: api.messenger.GetMessagesResponse
	(*MessagesNotModified)(nil),             // 12: api.messenger.MessagesNotModified
	(*MessagesSlice)(nil),                   // 13: api.messenger.MessagesSlice
	(*GetUnreadDialogsCounterRequest)(nil),  // 14: api.messenger.GetUnreadDialogsCounterRequest
	(*GetUnreadDialogsCounterResponse)(nil), // 15: api.messenger.GetUnreadDialogsCounterResponse
	(*Peer)(nil),                            // 16: api.messenger.Peer
	(*Message)(nil),                         // 17: api.messenger.Message
	(*Dialog)(nil),                          // 18: api.messenger.Dialog
	(*User)(nil),                            // 19: api.users.User
	(*timestamp.Timestamp)(nil),             // 20: google.protobuf.Timestamp
}
var file_api_messenger_messenger_service_proto_depIdxs = []int32{
	16, // 0: api.messenger.SendMessageRequest.peer:type_name -> api.messenger.Peer
	17, // 1: api.messenger.SendMessageResponse.message:type_name -> api.messenger.Message
	16, // 2: api.messenger.ReadMessageRequest.peer:type_name -> api.messenger.Peer
	16, // 3: api.messenger.GetDialogRequest.peer:type_name -> api.messenger.Peer
	18, // 4: api.messenger.GetDialogResponse.dialog:type_name -> api.messenger.Dialog
	17, // 5: api.messenger.GetDialogResponse.last_message:type_name -> api.messenger.Message
	19, // 6: api.messenger.GetDialogResponse.user:type_name -> api.users.User
	20, // 7: api.messenger.GetDialogsRequest.offset_date:type_name -> google.protobuf.Timestamp
	8,  // 8: api.messenger.GetDialogsResponse.not_modified:type_name -> api.messenger.DialogsNotModified
	9,  // 9: api.messenger.GetDialogsResponse.slice:type_name -> api.messenger.DialogsSlice
	18, // 10: api.messenger.DialogsSlice.dialogs:type_name -> api.messenger.Dialog
	17, // 11: api.messenger.DialogsSlice.messages:type_name -> api.messenger.Message
	19, // 12: api.messenger.DialogsSlice.users:type_name -> api.users.User
	16, // 13: api.messenger.GetMessagesRequest.peer:type_name -> api.messenger.Peer
	12, // 14: api.messenger.GetMessagesResponse.not_modified:type_name -> api.messenger.MessagesNotModified
	13, // 15: api.messenger.GetMessagesResponse.slice:type_name -> api.messenger.MessagesSlice
	17, // 16: api.messenger.MessagesSlice.messages:type_name -> api.messenger.Message
	19, // 17: api.messenger.MessagesSlice.users:type_name -> api.users.User
	0,  // 18: api.messenger.Messenger.SendMessage:input_type -> api.messenger.SendMessageRequest
	2,  // 19: api.messenger.Messenger.ReadMessage:input_type -> api.messenger.ReadMessageRequest
	4,  // 20: api.messenger.Messenger.GetDialog:input_type -> api.messenger.GetDialogRequest
	6,  // 21: api.messenger.Messenger.GetDialogs:input_type -> api.messenger.GetDialogsRequest
	10, // 22: api.messenger.Messenger.GetMessages:input_type -> api.messenger.GetMessagesRequest
	14, // 23: api.messenger.Messenger.GetUnreadDialogsCounter:input_type -> api.messenger.GetUnreadDialogsCounterRequest
	1,  // 24: api.messenger.Messenger.SendMessage:output_type -> api.messenger.SendMessageResponse
	3,  // 25: api.messenger.Messenger.ReadMessage:output_type -> api.messenger.ReadMessageResponse
	5,  // 26: api.messenger.Messenger.GetDialog:output_type -> api.messenger.GetDialogResponse
	7,  // 27: api.messenger.Messenger.GetDialogs:output_type -> api.messenger.GetDialogsResponse
	11, // 28: api.messenger.Messenger.GetMessages:output_type -> api.messenger.GetMessagesResponse
	15, // 29: api.messenger.Messenger.GetUnreadDialogsCounter:output_type -> api.messenger.GetUnreadDialogsCounterResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_messenger_messenger_service_proto_init() }
func file_api_messenger_messenger_service_proto_init() {
	if File_api_messenger_messenger_service_proto != nil {
		return
	}
	file_api_messenger_dialog_proto_init()
	file_api_messenger_message_proto_init()
	file_api_messenger_peer_proto_init()
	file_api_users_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_messenger_messenger_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDialogsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogsNotModified); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DialogsSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessagesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMessagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagesNotModified); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessagesSlice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnreadDialogsCounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_messenger_messenger_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUnreadDialogsCounterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_messenger_messenger_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SendMessageResponse_Message)(nil),
	}
	file_api_messenger_messenger_service_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_api_messenger_messenger_service_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*GetDialogsResponse_NotModified)(nil),
		(*GetDialogsResponse_Slice)(nil),
	}
	file_api_messenger_messenger_service_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_api_messenger_messenger_service_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*GetMessagesResponse_NotModified)(nil),
		(*GetMessagesResponse_Slice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_messenger_messenger_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_messenger_messenger_service_proto_goTypes,
		DependencyIndexes: file_api_messenger_messenger_service_proto_depIdxs,
		MessageInfos:      file_api_messenger_messenger_service_proto_msgTypes,
	}.Build()
	File_api_messenger_messenger_service_proto = out.File
	file_api_messenger_messenger_service_proto_rawDesc = nil
	file_api_messenger_messenger_service_proto_goTypes = nil
	file_api_messenger_messenger_service_proto_depIdxs = nil
}
